### PR TITLE
Add rclone to conda-requirements.txt

### PR DESCRIPTION
**Pull request by annefou**

### CODE REVIEW

**Comment by annefou** [comment]
@minrk I also would like to add the associated configuration files but I am not sure where to add them.

**Comment by minrk** [comment]
what files should go where? That probably belongs in the Dockerfile

**Review by minrk — APPROVED** [review]

**Comment by annefou** [comment]
> what files should go where? That probably belongs in the Dockerfile

that is what I thought but we also need to have the user credentials for our buckets.

Below is what I have put in `$HOME/.config/rclone/rclone.conf` (manually and with correct access_key_id and secret_access_key):
```
[cmarine]
type = s3
provider = Other
endpoint = https://s3.waw3-1.cloudferro.com
acl = public-read

[gfts]
type = s3
provider = Other
env_auth = true
access_key_id = XXX
secret_access_key = YYY
endpoint = https://s3.gra.perf.cloud.ovh.net
profile = gfts
region = gra
```

**Comment by minrk** [comment]
it shouldn't need the access key or profile with env_auth = true, so I think the same file works for everyone. This config worked for me:

```
[gfts]
type = s3
provider = Other
env_auth = true
region = gra
endpoint = https://s3.gra.perf.cloud.ovh.net
```

**Comment by annefou** [comment]
then I can add it in the repo and docker file, right?

**Comment by minrk** [comment]
We'll still need to copy it into home in an initContainer [here](https://github.com/destination-earth/DestinE_ESA_GFTS/blob/1a30002665db2ffccba1137d9c38d76e866fc4d0/jupyterhub/gfts-hub/values.yaml#L48), so might as well create it there, rather than needing to update the image.

I can do that, if you want.

**Comment by annefou** [comment]
> We'll still need to copy it into home in an initContainer [here](https://github.com/destination-earth/DestinE_ESA_GFTS/blob/1a30002665db2ffccba1137d9c38d76e866fc4d0/jupyterhub/gfts-hub/values.yaml#L48), so might as well create it there, rather than needing to update the image.
> 
> I can do that, if you want.

Out of curiosity, why can't we copy it in the docker file (and have the config file in https://github.com/destination-earth/DestinE_ESA_GFTS/tree/main/jupyterhub/images/user) e.g. updating the current Dockerfile with something like:

```
WORKDIR /home/$NB_USER
RUN mkdir -p ./.config/rclone
COPY rclone.conf ./.config/rclone
```

**Comment by annefou** [comment]
Ok! I got it. just to understand: in [here](https://github.com/destination-earth/DestinE_ESA_GFTS/blob/1a30002665db2ffccba1137d9c38d76e866fc4d0/jupyterhub/gfts-hub/values.yaml#L48), would you generate the config file on the fly?

**Comment by minrk** [comment]
yes, that's right

**Comment by annefou** [comment]
Ok. then let me try...

**Pull request merged**
