### PR TITLE
add users from VLIZ

### PR DESCRIPTION
**Pull request by tinaok**
We will start to use add more users.  
How do we want to proceed?

Can we make a procedure for clearing new users?

### CODE REVIEW

**Comment by annefou** [comment]
@tinaok What level of access does davidcasalsVLIZ need for the S3 buckets?

Read-only access to the gfts-reference-data and destine-gfts-data-lake S3 buckets? Or is there a need for write access as well?

What about the Ifremer bucket? Does he need read/write access to the gfts-ifremer bucket?

**Comment by tinaok** [comment]
Thank you Anne,

>Read-only access to the gfts-reference-data and destine-gfts-data-lake S3 buckets? Or is there a need for write access as well?
yes, read only there.

**Comment by annefou** [comment]
@minrk I tried to add the new buckets `gfts-vliz` and `vliz_users`. Could you check if everything is set up correctly, and that I haven’t messed up anything? Thanks!

**Comment by minrk** [comment]
> Can we make a procedure for clearing new users?

We do have a procedure [here](https://destination-earth.github.io/DestinE_ESA_GFTS/admin_hub.html#getting-access-to-the-gfts-hub-and-s3-buckets).

We can add docs for creating the buckets for new users.

@annefou looks right! I noticed a couple things that needed fixing in #93, and I'll apply those here as well (mainly a default deny permission that seems like it is supposed to be the s3 default, but isn't when I test).

**Comment by annefou** [comment]
> We can add docs for creating the buckets for new users.

Do you mean that `gfts-vliz` needs to be created manually and separately?

**Comment by minrk** [comment]
> Do you mean that gfts-vliz needs to be created manually and separately?

No, I mean what you did in this PR, which was exactly right, it is just a lot of copying and pasting we haven't written down yet.

I think it can actually be simplified a bit, too.

**Comment by minrk** [comment]
Any more you want to do here, or ok to merge?

**Comment by annefou** [comment]
For me it is OK to merge.

**Comment by minrk** [comment]
ok, the bucket exists and the user should have access to the Hub when the github action finishes deploying

**Comment by annefou** [comment]
Perfect! I will add some info on adding new buckets in the doc. Thank you!

**Pull request merged**
